"""
NetScan Pro - Report Generator Module
Compiles all scan findings into a structured PDF and/or HTML
penetration test report.

Usage (internal):
    gen = ReportGenerator(session_id, target, hosts, web_findings, cve_findings, output_format)
    paths = gen.generate()
"""

import os
from datetime import datetime
from jinja2 import Environment, FileSystemLoader, select_autoescape
from modules.logger import get_logger

logger = get_logger(__name__)

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")

SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Informational": 4, "None": 5}


class ReportGenerator:
    """
    Generates a professional penetration test report from scan results.
    Supports PDF (via ReportLab) and HTML (via Jinja2) output formats.
    """

    def __init__(self, session_id: str, target: str, hosts: list,
                 web_findings: list, cve_findings: list, output_format: str = "both"):
        self.session_id   = session_id
        self.target       = target
        self.hosts        = hosts
        self.web_findings = web_findings
        self.cve_findings = cve_findings
        self.output_format = output_format
        self.generated_at  = datetime.now()

        os.makedirs(OUTPUT_DIR, exist_ok=True)

    def generate(self) -> list:
        """Generate reports in the requested format(s). Returns list of file paths."""
        paths = []
        filename_base = f"netscampro_report_{self.session_id}_{self.generated_at.strftime('%Y%m%d_%H%M%S')}"

        if self.output_format in ("html", "both"):
            html_path = os.path.join(OUTPUT_DIR, f"{filename_base}.html")
            self._generate_html(html_path)
            paths.append(html_path)
            logger.info(f"HTML report saved: {html_path}")

        if self.output_format in ("pdf", "both"):
            pdf_path = os.path.join(OUTPUT_DIR, f"{filename_base}.pdf")
            try:
                self._generate_pdf(pdf_path)
                paths.append(pdf_path)
                logger.info(f"PDF report saved: {pdf_path}")
            except ImportError:
                logger.warning("ReportLab not installed. Skipping PDF. Install: pip install reportlab")

        return paths

    # ── DATA PREPARATION ─────────────────────────────────

    def _build_context(self) -> dict:
        """Build the template context dict used for both HTML and PDF."""
        all_findings = self._merge_findings()
        severity_counts = self._count_severity(all_findings)
        risk_rating = self._overall_risk(severity_counts)

        return {
            "report_title":    "NetScan Pro — Penetration Test Report",
            "session_id":      self.session_id,
            "target":          self.target,
            "generated_at":    self.generated_at.strftime("%d %B %Y, %H:%M:%S"),
            "total_hosts":     len(self.hosts),
            "total_findings":  len(all_findings),
            "severity_counts": severity_counts,
            "risk_rating":     risk_rating,
            "hosts":           self.hosts,
            "web_findings":    sorted(self.web_findings, key=lambda f: SEVERITY_ORDER.get(f.get("severity", "None"), 5)),
            "cve_findings":    sorted(self.cve_findings, key=lambda f: -(f.get("cvss_score") or 0)),
            "all_findings":    all_findings,
            "institution":     "Federal University of Petroleum Resources, Effurun (FUPRE)",
            "author":          "Obeh",
            "disclaimer":      (
                "This report was generated by NetScan Pro for authorized security assessment purposes only. "
                "All testing was conducted in a controlled lab environment with explicit permission. "
                "Unauthorized use of this tool against systems you do not own is illegal."
            )
        }

    def _merge_findings(self) -> list:
        """Merge web and CVE findings into a unified sorted list."""
        merged = []
        for f in self.web_findings:
            merged.append({**f, "source": "Web Tester", "id": f.get("vuln_type")})
        for f in self.cve_findings:
            merged.append({
                **f,
                "source":      "CVE Mapper",
                "id":          f.get("cve_id"),
                "vuln_type":   f.get("cve_id"),
                "description": f.get("description"),
                "url":         f.get("reference"),
            })
        return sorted(merged, key=lambda x: SEVERITY_ORDER.get(x.get("severity", "None"), 5))

    def _count_severity(self, findings: list) -> dict:
        counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "None": 0}
        for f in findings:
            sev = f.get("severity", "None")
            if sev in counts:
                counts[sev] += 1
        return counts

    def _overall_risk(self, counts: dict) -> str:
        if counts["Critical"] > 0:   return "CRITICAL"
        if counts["High"] > 0:        return "HIGH"
        if counts["Medium"] > 0:      return "MEDIUM"
        if counts["Low"] > 0:         return "LOW"
        return "INFORMATIONAL"

    # ── HTML REPORT ───────────────────────────────────────

    def _generate_html(self, output_path: str):
        """Render the HTML report using Jinja2 templates."""
        env = Environment(
            loader=FileSystemLoader(TEMPLATE_DIR),
            autoescape=select_autoescape(["html"])
        )
        template = env.get_template("report.html")
        context = self._build_context()
        html = template.render(**context)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

    # ── PDF REPORT ────────────────────────────────────────

    def _generate_pdf(self, output_path: str):
        """Generate a PDF report using ReportLab."""
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                         Table, TableStyle, HRFlowable, PageBreak)

        ctx = self._build_context()
        doc = SimpleDocTemplate(output_path, pagesize=A4,
                                topMargin=2*cm, bottomMargin=2*cm,
                                leftMargin=2*cm, rightMargin=2*cm)

        styles = getSampleStyleSheet()
        story  = []

        # ── Styles
        title_style = ParagraphStyle("Title", parent=styles["Title"],
                                     fontSize=22, textColor=colors.HexColor("#1F3864"),
                                     spaceAfter=6)
        h1_style    = ParagraphStyle("H1", parent=styles["Heading1"],
                                     fontSize=14, textColor=colors.HexColor("#1F3864"),
                                     spaceBefore=14, spaceAfter=4)
        h2_style    = ParagraphStyle("H2", parent=styles["Heading2"],
                                     fontSize=11, textColor=colors.HexColor("#2E75B6"),
                                     spaceBefore=10, spaceAfter=4)
        body_style  = ParagraphStyle("Body", parent=styles["Normal"],
                                     fontSize=9, leading=14, spaceAfter=4)
        small_style = ParagraphStyle("Small", parent=styles["Normal"],
                                     fontSize=8, leading=12, textColor=colors.grey)

        SEVERITY_COLORS = {
            "Critical": colors.HexColor("#C00000"),
            "High":     colors.HexColor("#E74C3C"),
            "Medium":   colors.HexColor("#E67E22"),
            "Low":      colors.HexColor("#2980B9"),
            "None":     colors.grey,
        }

        # ── Title Page
        story.append(Spacer(1, 1.5*cm))
        story.append(Paragraph(ctx["report_title"], title_style))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#2E75B6")))
        story.append(Spacer(1, 0.4*cm))

        meta = [
            ["Target",         ctx["target"]],
            ["Session ID",     ctx["session_id"]],
            ["Generated",      ctx["generated_at"]],
            ["Total Hosts",    str(ctx["total_hosts"])],
            ["Total Findings", str(ctx["total_findings"])],
            ["Overall Risk",   ctx["risk_rating"]],
        ]
        meta_table = Table(meta, colWidths=[4*cm, 12*cm])
        meta_table.setStyle(TableStyle([
            ("FONTNAME",     (0,0), (-1,-1), "Helvetica"),
            ("FONTSIZE",     (0,0), (-1,-1), 9),
            ("FONTNAME",     (0,0), (0,-1), "Helvetica-Bold"),
            ("TEXTCOLOR",    (0,0), (0,-1), colors.HexColor("#1F3864")),
            ("ROWBACKGROUNDS",(0,0),(-1,-1),[colors.HexColor("#EBF3FB"), colors.white]),
            ("GRID",         (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
            ("LEFTPADDING",  (0,0), (-1,-1), 6),
            ("RIGHTPADDING", (0,0), (-1,-1), 6),
            ("TOPPADDING",   (0,0), (-1,-1), 4),
            ("BOTTOMPADDING",(0,0), (-1,-1), 4),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph(ctx["disclaimer"], small_style))
        story.append(PageBreak())

        # ── Hosts Summary
        story.append(Paragraph("1. Discovered Hosts", h1_style))
        if ctx["hosts"]:
            for host in ctx["hosts"]:
                story.append(Paragraph(f"▸ {host['ip']} — {host.get('hostname','N/A')} — OS: {host.get('os','Unknown')}", body_style))
                port_data = [["Port", "Protocol", "State", "Service", "Version"]]
                for p in host.get("ports", []):
                    port_data.append([str(p["port"]), p.get("protocol","tcp"),
                                      p.get("state","open"), p.get("service","?"),
                                      str(p.get("version","N/A"))[:40]])
                if len(port_data) > 1:
                    t = Table(port_data, colWidths=[2*cm, 2.5*cm, 2*cm, 3.5*cm, 6*cm])
                    t.setStyle(TableStyle([
                        ("BACKGROUND",  (0,0), (-1,0), colors.HexColor("#1F3864")),
                        ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
                        ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"),
                        ("FONTSIZE",    (0,0), (-1,-1), 8),
                        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#F5F9FF")]),
                        ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                        ("LEFTPADDING", (0,0), (-1,-1), 4),
                        ("TOPPADDING",  (0,0), (-1,-1), 3),
                        ("BOTTOMPADDING",(0,0),(-1,-1), 3),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 0.3*cm))
        else:
            story.append(Paragraph("No live hosts discovered.", body_style))

        story.append(PageBreak())

        # ── Web Findings
        story.append(Paragraph("2. Web Application Findings", h1_style))
        if ctx["web_findings"]:
            for i, f in enumerate(ctx["web_findings"], 1):
                sev_color = SEVERITY_COLORS.get(f.get("severity","None"), colors.grey)
                story.append(Paragraph(f"Finding {i}: {f.get('vuln_type','N/A')}", h2_style))
                finding_data = [
                    ["Severity",        f.get("severity","N/A")],
                    ["Host",            f.get("host_ip","N/A")],
                    ["URL",             str(f.get("url","N/A"))[:80]],
                    ["Description",     f.get("description","N/A")],
                    ["Evidence",        str(f.get("evidence","N/A"))[:150]],
                    ["Recommendation",  f.get("recommendation","N/A")],
                ]
                ft = Table(finding_data, colWidths=[3.5*cm, 12.5*cm])
                ft.setStyle(TableStyle([
                    ("FONTNAME",  (0,0), (-1,-1), "Helvetica"),
                    ("FONTNAME",  (0,0), (0,-1), "Helvetica-Bold"),
                    ("FONTSIZE",  (0,0), (-1,-1), 8),
                    ("TEXTCOLOR", (0,0), (0,0), sev_color),
                    ("ROWBACKGROUNDS",(0,0),(-1,-1),[colors.HexColor("#FFF8F8"), colors.white]),
                    ("GRID",      (0,0), (-1,-1), 0.5, colors.HexColor("#DDDDDD")),
                    ("LEFTPADDING",(0,0),(-1,-1), 5),
                    ("TOPPADDING",(0,0),(-1,-1), 3),
                    ("BOTTOMPADDING",(0,0),(-1,-1), 3),
                    ("VALIGN",    (0,0), (-1,-1), "TOP"),
                ]))
                story.append(ft)
                story.append(Spacer(1, 0.3*cm))
        else:
            story.append(Paragraph("No web vulnerabilities detected.", body_style))

        story.append(PageBreak())

        # ── CVE Findings
        story.append(Paragraph("3. CVE Findings", h1_style))
        if ctx["cve_findings"]:
            cve_table_data = [["CVE ID", "Host", "Port", "Service", "CVSS", "Severity"]]
            for f in ctx["cve_findings"]:
                sev = f.get("severity","N/A")
                cve_table_data.append([
                    f.get("cve_id","N/A"), f.get("host_ip","N/A"),
                    str(f.get("port","N/A")), str(f.get("service","N/A"))[:25],
                    str(f.get("cvss_score","N/A")), sev
                ])
            ct = Table(cve_table_data, colWidths=[3*cm, 3*cm, 1.5*cm, 4*cm, 1.5*cm, 3*cm])
            ct.setStyle(TableStyle([
                ("BACKGROUND",  (0,0), (-1,0), colors.HexColor("#1F3864")),
                ("TEXTCOLOR",   (0,0), (-1,0), colors.white),
                ("FONTNAME",    (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE",    (0,0), (-1,-1), 8),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, colors.HexColor("#F5F9FF")]),
                ("GRID",        (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                ("LEFTPADDING", (0,0), (-1,-1), 4),
                ("TOPPADDING",  (0,0), (-1,-1), 3),
                ("BOTTOMPADDING",(0,0),(-1,-1), 3),
            ]))
            story.append(ct)
        else:
            story.append(Paragraph("No CVE findings recorded.", body_style))

        doc.build(story)
