"""
CyberScan Pro - Professional Report Generator
Generates PDF and HTML penetration test reports.
"""

import os
from datetime import datetime
from jinja2 import Environment, FileSystemLoader, select_autoescape
from modules.logger import get_logger

logger = get_logger(__name__)

OUTPUT_DIR   = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")
SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "None": 4}


class ReportGenerator:

    def __init__(self, session_id, target, hosts, web_findings,
                 cve_findings, output_format="both"):
        self.session_id    = session_id
        self.target        = target
        self.hosts         = hosts
        self.web_findings  = web_findings
        self.cve_findings  = cve_findings
        self.output_format = output_format
        self.generated_at  = datetime.now()
        os.makedirs(OUTPUT_DIR, exist_ok=True)

    def generate(self) -> list:
        paths = []
        base  = f"cyberscanpro_report_{self.session_id}_{self.generated_at.strftime('%Y%m%d_%H%M%S')}"

        if self.output_format in ("html", "both"):
            p = os.path.join(OUTPUT_DIR, f"{base}.html")
            self._generate_html(p)
            paths.append(p)
            logger.info(f"HTML report saved: {p}")

        if self.output_format in ("pdf", "both"):
            p = os.path.join(OUTPUT_DIR, f"{base}.pdf")
            self._generate_pdf(p)
            paths.append(p)
            logger.info(f"PDF report saved: {p}")

        return paths

    # ── CONTEXT ───────────────────────────────────────────────────────────────

    def _build_context(self) -> dict:
        all_findings = self._merge_findings()
        counts       = self._count_severity(all_findings)
        return {
            "report_title":   "Vulnerability Assessment Report",
            "target":         self.target,
            "session_id":     self.session_id,
            "generated_at":   self.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC"),
            "total_hosts":    len(self.hosts),
            "total_findings": len(all_findings),
            "risk_rating":    self._overall_risk(counts),
            "severity_counts": counts,
            "hosts":          self.hosts,
            "web_findings":   sorted(self.web_findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity","None"), 4)),
            "cve_findings":   sorted(self.cve_findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity","None"), 4)),
            "all_findings":   all_findings,
            "disclaimer":     "This report was generated by CyberScan Pro for authorized security assessment purposes only. "
                              "Unauthorized use of this tool or its findings is strictly prohibited. "
                              "FUPRE Final Year Project — Obeh Emmanuel Onoriode (Cos/9581/2022).",
            "methodology":    [
                ("Reconnaissance",    "DNS resolution, subdomain discovery, and target enumeration."),
                ("Network Scanning",  "TCP port scanning using Nmap/socket scanning to identify open services."),
                ("Service Detection", "Banner grabbing and version fingerprinting on discovered ports."),
                ("Web Assessment",    "HTTP security header analysis, vulnerability testing (SQLi, XSS, CSRF, Traversal)."),
                ("CVE Mapping",       "Mapping discovered services to known CVEs via NVD API with CVSS scoring."),
                ("Reporting",         "Automated PDF/HTML report generation with risk scoring and remediation guidance."),
            ]
        }

    def _merge_findings(self) -> list:
        merged = []
        for f in self.web_findings:
            merged.append({
                "type": "Web", "severity": f.get("severity"),
                "title": f.get("vuln_type"), "host": f.get("host_ip"),
                "detail": f.get("description"), "url": f.get("url"),
            })
        for f in self.cve_findings:
            merged.append({
                "type": "CVE", "severity": f.get("severity"),
                "title": f.get("cve_id"), "host": f.get("host_ip"),
                "detail": f.get("description"), "url": f.get("reference"),
            })
        return sorted(merged, key=lambda x: SEVERITY_ORDER.get(x.get("severity","None"), 4))

    def _count_severity(self, findings):
        counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "None": 0}
        for f in findings:
            sev = f.get("severity", "None")
            if sev in counts:
                counts[sev] += 1
        return counts

    def _overall_risk(self, counts):
        if counts["Critical"] > 0: return "CRITICAL"
        if counts["High"] > 0:     return "HIGH"
        if counts["Medium"] > 0:   return "MEDIUM"
        if counts["Low"] > 0:      return "LOW"
        return "INFORMATIONAL"

    # ── HTML ──────────────────────────────────────────────────────────────────

    def _generate_html(self, path):
        env      = Environment(loader=FileSystemLoader(TEMPLATE_DIR),
                               autoescape=select_autoescape(["html"]))
        template = env.get_template("report.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(template.render(**self._build_context()))

    # ── PDF ───────────────────────────────────────────────────────────────────

    def _generate_pdf(self, path):
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                        Table, TableStyle, HRFlowable, PageBreak,
                                        KeepTogether)
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        ctx = self._build_context()
        doc = SimpleDocTemplate(path, pagesize=A4,
                                topMargin=2*cm, bottomMargin=2.5*cm,
                                leftMargin=2*cm, rightMargin=2*cm,
                                title=ctx["report_title"],
                                author="CyberScan Pro — Obeh Emmanuel Onoriode")

        # ── Color palette
        DARK_BLUE   = colors.HexColor("#0D1B2A")
        MID_BLUE    = colors.HexColor("#1F3864")
        ACCENT      = colors.HexColor("#2E75B6")
        LIGHT_BLUE  = colors.HexColor("#EBF3FB")
        CRITICAL    = colors.HexColor("#C00000")
        HIGH        = colors.HexColor("#E74C3C")
        MEDIUM      = colors.HexColor("#E67E22")
        LOW         = colors.HexColor("#2980B9")
        NONE_COLOR  = colors.HexColor("#95A5A6")

        SEV_COLORS = {"Critical": CRITICAL, "High": HIGH,
                      "Medium": MEDIUM, "Low": LOW, "None": NONE_COLOR}

        styles = getSampleStyleSheet()

        def style(name, **kw):
            return ParagraphStyle(name, parent=styles["Normal"], **kw)

        COVER_TITLE  = style("CT", fontSize=28, textColor=colors.white,
                             fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=8)
        COVER_SUB    = style("CS", fontSize=13, textColor=colors.HexColor("#A8C4D8"),
                             alignment=TA_CENTER, spaceAfter=6)
        COVER_BODY   = style("CB", fontSize=10, textColor=colors.HexColor("#A8C4D8"),
                             alignment=TA_CENTER, spaceAfter=4)
        H1           = style("H1", fontSize=14, textColor=MID_BLUE,
                             fontName="Helvetica-Bold", spaceBefore=16, spaceAfter=6)
        H2           = style("H2", fontSize=11, textColor=ACCENT,
                             fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4)
        BODY         = style("BD", fontSize=9, leading=14, spaceAfter=4)
        SMALL        = style("SM", fontSize=7.5, textColor=colors.grey, leading=11)
        CODE         = style("CD", fontSize=8, fontName="Courier",
                             textColor=colors.HexColor("#2C3E50"), leading=12)

        story = []

        # ════════════════════════════════════════════════════
        # COVER PAGE
        # ════════════════════════════════════════════════════
        # Dark header block
        cover_header = Table(
            [[Paragraph("NETSCAMPRO", COVER_TITLE)],
             [Paragraph("Automated Vulnerability Assessment Report", COVER_SUB)],
             [Paragraph(f"Target: {ctx['target']}", COVER_BODY)],
             [Paragraph(f"Generated: {ctx['generated_at']}", COVER_BODY)],
             [Paragraph(f"Session ID: {ctx['session_id']}", COVER_BODY)]],
            colWidths=[16*cm]
        )
        cover_header.setStyle(TableStyle([
            ("BACKGROUND",   (0,0), (-1,-1), DARK_BLUE),
            ("TOPPADDING",   (0,0), (-1,-1), 16),
            ("BOTTOMPADDING",(0,0), (-1,-1), 16),
            ("LEFTPADDING",  (0,0), (-1,-1), 20),
            ("RIGHTPADDING", (0,0), (-1,-1), 20),
            ("ROUNDEDCORNERS", (0,0), (-1,-1), 8),
        ]))
        story.append(Spacer(1, 1.5*cm))
        story.append(cover_header)
        story.append(Spacer(1, 0.8*cm))

        # Risk rating banner
        risk = ctx["risk_rating"]
        risk_color = {"CRITICAL": CRITICAL, "HIGH": HIGH,
                      "MEDIUM": MEDIUM, "LOW": LOW}.get(risk, NONE_COLOR)
        risk_table = Table(
            [[Paragraph(f"OVERALL RISK: {risk}",
                        style("RT", fontSize=16, textColor=colors.white,
                              fontName="Helvetica-Bold", alignment=TA_CENTER))]],
            colWidths=[16*cm]
        )
        risk_table.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), risk_color),
            ("TOPPADDING",    (0,0), (-1,-1), 12),
            ("BOTTOMPADDING", (0,0), (-1,-1), 12),
        ]))
        story.append(risk_table)
        story.append(Spacer(1, 0.8*cm))

        # Summary stats
        counts = ctx["severity_counts"]
        stats_data = [
            ["Hosts Found", "Total Findings", "Critical", "High", "Medium", "Low"],
            [str(ctx["total_hosts"]), str(ctx["total_findings"]),
             str(counts["Critical"]), str(counts["High"]),
             str(counts["Medium"]), str(counts["Low"])]
        ]
        stats_table = Table(stats_data, colWidths=[2.67*cm]*6)
        stats_table.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0), MID_BLUE),
            ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
            ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTNAME",      (0,1), (-1,1), "Helvetica-Bold"),
            ("FONTSIZE",      (0,0), (-1,-1), 9),
            ("FONTSIZE",      (0,1), (-1,1), 14),
            ("ALIGN",         (0,0), (-1,-1), "CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[LIGHT_BLUE]),
            ("GRID",          (0,0), (-1,-1), 0.5, colors.white),
            ("TOPPADDING",    (0,0), (-1,-1), 8),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("TEXTCOLOR",     (2,1), (2,1), CRITICAL),
            ("TEXTCOLOR",     (3,1), (3,1), HIGH),
            ("TEXTCOLOR",     (4,1), (4,1), MEDIUM),
            ("TEXTCOLOR",     (5,1), (5,1), LOW),
        ]))
        story.append(stats_table)
        story.append(Spacer(1, 0.8*cm))
        story.append(Paragraph(ctx["disclaimer"], SMALL))
        story.append(PageBreak())

        # ════════════════════════════════════════════════════
        # SECTION 1: EXECUTIVE SUMMARY
        # ════════════════════════════════════════════════════
        story.append(Paragraph("1. Executive Summary", H1))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3*cm))

        vuln_count = len(ctx["web_findings"]) + len(ctx["cve_findings"])
        summary_text = (
            f"An automated vulnerability assessment was conducted against <b>{ctx['target']}</b> "
            f"on {ctx['generated_at']}. The assessment discovered <b>{ctx['total_hosts']}</b> live host(s) "
            f"with a total of <b>{vuln_count}</b> security findings. "
            f"The overall risk rating for this target is <b>{risk}</b>. "
        )
        if counts["Critical"] > 0:
            summary_text += f"<b>{counts['Critical']} critical issue(s)</b> require immediate attention. "
        if counts["High"] > 0:
            summary_text += f"<b>{counts['High']} high severity issue(s)</b> should be addressed urgently. "
        summary_text += "Detailed findings and remediation guidance are provided in the sections below."
        story.append(Paragraph(summary_text, BODY))
        story.append(Spacer(1, 0.5*cm))

        # ════════════════════════════════════════════════════
        # SECTION 2: METHODOLOGY
        # ════════════════════════════════════════════════════
        story.append(Paragraph("2. Methodology", H1))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3*cm))

        method_data = [["Phase", "Description"]] + [[m[0], m[1]] for m in ctx["methodology"]]
        method_table = Table(method_data, colWidths=[4*cm, 12*cm])
        method_table.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0), MID_BLUE),
            ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
            ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTNAME",      (0,1), (0,-1), "Helvetica-Bold"),
            ("TEXTCOLOR",     (0,1), (0,-1), ACCENT),
            ("FONTSIZE",      (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
            ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
            ("LEFTPADDING",   (0,0), (-1,-1), 6),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("VALIGN",        (0,0), (-1,-1), "TOP"),
        ]))
        story.append(method_table)
        story.append(PageBreak())

        # ════════════════════════════════════════════════════
        # SECTION 3: DISCOVERED HOSTS
        # ════════════════════════════════════════════════════
        story.append(Paragraph("3. Discovered Hosts", H1))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3*cm))

        if ctx["hosts"]:
            for host in ctx["hosts"]:
                host_block = []
                host_block.append(Paragraph(
                    f"<b>{host['ip']}</b> — Hostname: {host.get('hostname','N/A')} — OS: {host.get('os','Unknown')} — Status: {host.get('status','up')}",
                    H2))
                port_data = [["Port", "Protocol", "State", "Service", "Version"]]
                for p in host.get("ports", []):
                    port_data.append([
                        str(p.get("port","")), p.get("protocol","tcp"),
                        p.get("state","open"), p.get("service","unknown"),
                        str(p.get("version","N/A"))[:45]
                    ])
                if len(port_data) > 1:
                    pt = Table(port_data, colWidths=[1.8*cm, 2.2*cm, 1.8*cm, 3.2*cm, 7*cm])
                    pt.setStyle(TableStyle([
                        ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
                        ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
                        ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
                        ("FONTSIZE",      (0,0), (-1,-1), 8),
                        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
                        ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                        ("LEFTPADDING",   (0,0), (-1,-1), 4),
                        ("TOPPADDING",    (0,0), (-1,-1), 3),
                        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
                    ]))
                    host_block.append(pt)
                else:
                    host_block.append(Paragraph("No open ports detected.", BODY))
                host_block.append(Spacer(1, 0.4*cm))
                story.append(KeepTogether(host_block))
        else:
            story.append(Paragraph("No live hosts discovered.", BODY))

        story.append(PageBreak())

        # ════════════════════════════════════════════════════
        # SECTION 4: WEB FINDINGS
        # ════════════════════════════════════════════════════
        story.append(Paragraph("4. Web Application Findings", H1))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3*cm))

        if ctx["web_findings"]:
            story.append(Paragraph(f"Total: {len(ctx['web_findings'])} finding(s)", SMALL))
            story.append(Spacer(1, 0.2*cm))
            for i, f in enumerate(ctx["web_findings"], 1):
                sev       = f.get("severity","None")
                sev_color = SEV_COLORS.get(sev, NONE_COLOR)
                block = []
                block.append(Paragraph(
                    f"<font color='#{sev_color.hexval()[2:]}'>■</font> "
                    f"Finding #{i}: {f.get('vuln_type','N/A')}",
                    H2))
                fd = [
                    ["Severity",       sev],
                    ["Host IP",        f.get("host_ip","N/A")],
                    ["URL",            str(f.get("url","N/A"))[:90]],
                    ["Description",    f.get("description","N/A")],
                    ["Evidence",       str(f.get("evidence","N/A"))[:200]],
                    ["Recommendation", f.get("recommendation","N/A")],
                ]
                ft = Table(fd, colWidths=[3.5*cm, 12.5*cm])
                ft.setStyle(TableStyle([
                    ("FONTNAME",      (0,0), (-1,-1), "Helvetica"),
                    ("FONTNAME",      (0,0), (0,-1), "Helvetica-Bold"),
                    ("FONTSIZE",      (0,0), (-1,-1), 8),
                    ("TEXTCOLOR",     (1,0), (1,0), sev_color),
                    ("FONTNAME",      (1,0), (1,0), "Helvetica-Bold"),
                    ("ROWBACKGROUNDS",(0,0),(-1,-1),[colors.HexColor("#FFF8F8"), colors.white]),
                    ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#DDDDDD")),
                    ("LEFTPADDING",   (0,0), (-1,-1), 5),
                    ("TOPPADDING",    (0,0), (-1,-1), 3),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 3),
                    ("VALIGN",        (0,0), (-1,-1), "TOP"),
                ]))
                block.append(ft)
                block.append(Spacer(1, 0.3*cm))
                story.append(KeepTogether(block))
        else:
            story.append(Paragraph("No web vulnerabilities detected.", BODY))

        story.append(PageBreak())

        # ════════════════════════════════════════════════════
        # SECTION 5: CVE FINDINGS
        # ════════════════════════════════════════════════════
        story.append(Paragraph("5. CVE Findings", H1))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3*cm))

        if ctx["cve_findings"]:
            story.append(Paragraph(f"Total: {len(ctx['cve_findings'])} CVE(s)", SMALL))
            story.append(Spacer(1, 0.2*cm))
            cve_data = [["CVE ID", "Host", "Port", "Service", "CVSS", "Severity"]]
            for f in ctx["cve_findings"]:
                sev = f.get("severity","N/A")
                cve_data.append([
                    f.get("cve_id","N/A"),
                    f.get("host_ip","N/A"),
                    str(f.get("port","N/A")),
                    str(f.get("service","N/A"))[:28],
                    str(f.get("cvss_score","N/A")),
                    sev
                ])
            ct = Table(cve_data, colWidths=[3.2*cm, 2.8*cm, 1.4*cm, 4*cm, 1.4*cm, 3.2*cm])
            ct.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
                ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
                ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE",      (0,0), (-1,-1), 8),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
                ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                ("LEFTPADDING",   (0,0), (-1,-1), 4),
                ("TOPPADDING",    (0,0), (-1,-1), 3),
                ("BOTTOMPADDING", (0,0), (-1,-1), 3),
                ("ALIGN",         (4,0), (5,-1), "CENTER"),
            ]))
            # Color severity column
            for row_idx, f in enumerate(ctx["cve_findings"], 1):
                sev_col = SEV_COLORS.get(f.get("severity","None"), NONE_COLOR)
                ct.setStyle(TableStyle([
                    ("TEXTCOLOR",  (5, row_idx), (5, row_idx), sev_col),
                    ("FONTNAME",   (5, row_idx), (5, row_idx), "Helvetica-Bold"),
                ]))
            story.append(ct)

            # CVE descriptions
            story.append(Spacer(1, 0.5*cm))
            story.append(Paragraph("CVE Details:", H2))
            for f in ctx["cve_findings"]:
                desc_block = [
                    Paragraph(f"<b>{f.get('cve_id','N/A')}</b> — CVSS: {f.get('cvss_score','N/A')} — {f.get('severity','N/A')}", BODY),
                    Paragraph(f.get("description","No description available.")[:300], SMALL),
                    Spacer(1, 0.2*cm)
                ]
                story.append(KeepTogether(desc_block))
        else:
            story.append(Paragraph("No CVE findings recorded.", BODY))

        story.append(PageBreak())

        # ════════════════════════════════════════════════════
        # SECTION 6: REMEDIATION SUMMARY
        # ════════════════════════════════════════════════════
        story.append(Paragraph("6. Remediation Summary", H1))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3*cm))

        if ctx["web_findings"]:
            seen_recs = set()
            for f in ctx["web_findings"]:
                rec = f.get("recommendation","")
                vuln = f.get("vuln_type","")
                key = vuln[:50]
                if key not in seen_recs and rec:
                    seen_recs.add(key)
                    sev = f.get("severity","Low")
                    sev_color = SEV_COLORS.get(sev, NONE_COLOR)
                    story.append(Paragraph(
                        f"[{sev}] {vuln}", H2))
                    story.append(Paragraph(f"↳ {rec}", BODY))
                    story.append(Spacer(1, 0.2*cm))
        else:
            story.append(Paragraph("No remediation actions required.", BODY))

        # ── Footer disclaimer
        story.append(Spacer(1, 1*cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
        story.append(Spacer(1, 0.2*cm))
        story.append(Paragraph(
            "CyberScan Pro v1.0.0 | FUPRE Final Year Project | "
            "Obeh Emmanuel Onoriode (Cos/9581/2022) | "
            "⚠ This report is confidential. Authorized use only.",
            SMALL))

        doc.build(story)
