"""
CyberScan Pro - Professional Report Generator
Generates PDF and HTML reports with plain English explanations.
"""

import os
import sys
from datetime import datetime
from jinja2 import Environment, FileSystemLoader, select_autoescape
from modules.logger import get_logger
from modules.vuln_explanations import get_explanation

logger = get_logger(__name__)

OUTPUT_DIR   = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")
SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "None": 4}

METHODOLOGY = [
    ("1. Subdomain Discovery",  "Queried public APIs and performed DNS bruteforce to find subdomains", "Hidden attack surfaces and exposed services"),
    ("2. Network Scanning",     "TCP port scan using Nmap/socket scanner to find open ports and services", "Open ports, running services, software versions"),
    ("3. Service Detection",    "Banner grabbing and version fingerprinting on all open ports", "Outdated software, vulnerable service versions"),
    ("4. Web Assessment",       "HTTP security header analysis and vulnerability payload testing", "XSS, SQLi, CSRF, directory traversal, open redirects"),
    ("5. CVE Mapping",          "Queried the NVD (National Vulnerability Database) API", "Known CVEs matching detected service versions"),
    ("6. Risk Scoring",         "Calculated per-host risk scores based on finding severity", "Overall security posture and priority issues"),
]


class ReportGenerator:

    def __init__(self, session_id, target, hosts, web_findings,
                 cve_findings, output_format="both"):
        self.session_id    = session_id
        self.target        = target
        self.hosts         = hosts
        self.web_findings  = web_findings
        self.cve_findings  = cve_findings
        self.output_format = output_format
        self.generated_at  = datetime.now()
        os.makedirs(OUTPUT_DIR, exist_ok=True)

    def generate(self) -> list:
        paths = []
        base  = f"cyberscanpro_report_{self.session_id}_{self.generated_at.strftime('%Y%m%d_%H%M%S')}"

        if self.output_format in ("html", "both"):
            p = os.path.join(OUTPUT_DIR, f"{base}.html")
            self._generate_html(p)
            paths.append(p)
            logger.info(f"HTML report saved: {p}")

        if self.output_format in ("pdf", "both"):
            p = os.path.join(OUTPUT_DIR, f"{base}.pdf")
            self._generate_pdf(p)
            paths.append(p)
            logger.info(f"PDF report saved: {p}")

        return paths

    def _enrich_web_findings(self, findings):
        """Add plain English explanation fields to each web finding."""
        enriched = []
        for f in findings:
            exp = get_explanation(f.get("vuln_type", ""))
            f = dict(f)
            f["plain_what"]       = exp.get("what_it_is", "")
            f["plain_means"]      = exp.get("what_it_means", "")
            f["plain_impact"]     = exp.get("real_world_impact", "")
            f["plain_fix"]        = exp.get("how_to_fix", "")
            f["plain_difficulty"] = exp.get("difficulty", "")
            enriched.append(f)
        return enriched

    def _build_context(self) -> dict:
        web_enriched = self._enrich_web_findings(self.web_findings)
        all_findings = self._merge_findings(web_enriched)
        counts       = self._count_severity(all_findings)
        return {
            "report_title":    "Vulnerability Assessment Report",
            "target":          self.target,
            "session_id":      self.session_id,
            "generated_at":    self.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC"),
            "total_hosts":     len(self.hosts),
            "total_findings":  len(all_findings),
            "risk_rating":     self._overall_risk(counts),
            "severity_counts": counts,
            "hosts":           self.hosts,
            "web_findings":    sorted(web_enriched, key=lambda x: SEVERITY_ORDER.get(x.get("severity","None"), 4)),
            "cve_findings":    sorted(self.cve_findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity","None"), 4)),
            "all_findings":    all_findings,
            "methodology":     METHODOLOGY,
            "disclaimer":      (
                "This report was generated by CyberScan Pro for authorized security assessment purposes only. "
                "Unauthorized use of this tool or its findings is strictly prohibited. "
                "FUPRE Final Year Project — Obeh Emmanuel Onoriode (Cos/9581/2022)."
            ),
        }

    def _merge_findings(self, web_findings) -> list:
        merged = []
        for f in web_findings:
            merged.append({
                "type":     "Web",
                "severity": f.get("severity"),
                "vuln_type": f.get("vuln_type"),
                "host_ip":  f.get("host_ip"),
                "recommendation": f.get("recommendation",""),
            })
        for f in self.cve_findings:
            merged.append({
                "type":     "CVE",
                "severity": f.get("severity"),
                "vuln_type": f.get("cve_id"),
                "host_ip":  f.get("host_ip"),
                "recommendation": f"Update {f.get('service','')} to the latest patched version.",
            })
        return sorted(merged, key=lambda x: SEVERITY_ORDER.get(x.get("severity","None"), 4))

    def _count_severity(self, findings):
        counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "None": 0}
        for f in findings:
            sev = f.get("severity", "None")
            if sev in counts:
                counts[sev] += 1
        return counts

    def _overall_risk(self, counts):
        if counts["Critical"] > 0: return "CRITICAL"
        if counts["High"] > 0:     return "HIGH"
        if counts["Medium"] > 0:   return "MEDIUM"
        if counts["Low"] > 0:      return "LOW"
        return "INFORMATIONAL"

    def _generate_html(self, path):
        env      = Environment(
            loader=FileSystemLoader(TEMPLATE_DIR),
            autoescape=select_autoescape(["html"])
        )
        template = env.get_template("report.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(template.render(**self._build_context()))

    def _generate_pdf(self, path):
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib import colors
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                            Table, TableStyle, HRFlowable,
                                            PageBreak, KeepTogether)
            from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFIED
        except ImportError:
            logger.error("reportlab not installed — PDF generation skipped")
            return

        ctx = self._build_context()

        DARK_BLUE  = colors.HexColor("#1F3864")
        MID_BLUE   = colors.HexColor("#2E75B6")
        ACCENT     = colors.HexColor("#2E75B6")
        LIGHT_BLUE = colors.HexColor("#EBF3FB")
        CRITICAL   = colors.HexColor("#C00000")
        HIGH       = colors.HexColor("#E74C3C")
        MEDIUM     = colors.HexColor("#E67E22")
        LOW        = colors.HexColor("#2980B9")
        GREEN      = colors.HexColor("#27AE60")
        NONE_CLR   = colors.HexColor("#95A5A6")

        SEV_COLORS = {
            "Critical": CRITICAL, "High": HIGH,
            "Medium": MEDIUM, "Low": LOW, "None": NONE_CLR
        }
        RISK_COLORS = {
            "CRITICAL": CRITICAL, "HIGH": HIGH,
            "MEDIUM": MEDIUM, "LOW": LOW, "INFORMATIONAL": GREEN
        }

        doc = SimpleDocTemplate(
            path, pagesize=A4,
            topMargin=2*cm, bottomMargin=2.5*cm,
            leftMargin=2*cm, rightMargin=2*cm,
            title="CyberScan Pro — Vulnerability Assessment Report",
            author="Obeh Emmanuel Onoriode"
        )

        styles = getSampleStyleSheet()
        FONT = "Helvetica"

        def S(name, **kw):
            return ParagraphStyle(name, parent=styles["Normal"],
                                  fontName=FONT, **kw)

        TITLE  = S("T",  fontSize=22, textColor=colors.white,
                   fontName="Helvetica-Bold", alignment=TA_CENTER)
        SUB    = S("S",  fontSize=11, textColor=colors.HexColor("#A8C4D8"),
                   alignment=TA_CENTER)
        H1     = S("H1", fontSize=14, textColor=DARK_BLUE,
                   fontName="Helvetica-Bold", spaceBefore=14, spaceAfter=6)
        H2     = S("H2", fontSize=11, textColor=MID_BLUE,
                   fontName="Helvetica-Bold", spaceBefore=10, spaceAfter=4)
        BODY   = S("BD", fontSize=9,  leading=14, spaceAfter=4,
                   alignment=TA_JUSTIFIED)
        SMALL  = S("SM", fontSize=7.5, textColor=colors.grey, leading=11)
        LABEL  = S("LB", fontSize=8,  textColor=colors.grey,
                   fontName="Helvetica-Bold")
        PE     = S("PE", fontSize=8.5, leading=13, spaceAfter=3)

        def blank(h=0.3):
            return Spacer(1, h*cm)

        def hr():
            return HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC"))

        story = []

        # ── COVER PAGE ────────────────────────────────────────────────────────
        cover = Table([[
            Paragraph("🛡️ CyberScan Pro", TITLE),
            Paragraph("Vulnerability Assessment Report", SUB),
            Paragraph(f"Target: {ctx['target']}", SUB),
            Paragraph(f"Generated: {ctx['generated_at']}", SUB),
        ]], colWidths=[16*cm])
        cover.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), DARK_BLUE),
            ("TOPPADDING",    (0,0), (-1,-1), 16),
            ("BOTTOMPADDING", (0,0), (-1,-1), 16),
        ]))
        story += [blank(1.5), cover, blank(0.8)]

        risk = ctx["risk_rating"]
        risk_color = RISK_COLORS.get(risk, NONE_CLR)
        risk_tbl = Table([[
            Paragraph(f"OVERALL RISK: {risk}",
                      S("R", fontSize=16, textColor=colors.white,
                        fontName="Helvetica-Bold", alignment=TA_CENTER))
        ]], colWidths=[16*cm])
        risk_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,-1), risk_color),
            ("TOPPADDING",    (0,0), (-1,-1), 10),
            ("BOTTOMPADDING", (0,0), (-1,-1), 10),
        ]))
        story += [risk_tbl, blank(0.6)]

        counts = ctx["severity_counts"]
        stats = Table(
            [["Hosts", "Findings", "Critical", "High", "Medium", "Low"],
             [str(ctx["total_hosts"]), str(ctx["total_findings"]),
              str(counts["Critical"]), str(counts["High"]),
              str(counts["Medium"]), str(counts["Low"])]],
            colWidths=[2.67*cm]*6
        )
        stats.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
            ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
            ("FONTNAME",      (0,0), (-1,-1), "Helvetica-Bold"),
            ("FONTSIZE",      (0,0), (-1,-1), 9),
            ("FONTSIZE",      (0,1), (-1,1), 14),
            ("ALIGN",         (0,0), (-1,-1), "CENTER"),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[LIGHT_BLUE]),
            ("TOPPADDING",    (0,0), (-1,-1), 8),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("TEXTCOLOR",     (2,1), (2,1), CRITICAL),
            ("TEXTCOLOR",     (3,1), (3,1), HIGH),
            ("TEXTCOLOR",     (4,1), (4,1), MEDIUM),
            ("TEXTCOLOR",     (5,1), (5,1), LOW),
        ]))
        story += [stats, blank(0.6), Paragraph(ctx["disclaimer"], SMALL), PageBreak()]

        # ── EXECUTIVE SUMMARY ─────────────────────────────────────────────────
        story += [Paragraph("Executive Summary", H1), hr(), blank(0.2)]
        summary = (
            f"An automated vulnerability assessment was conducted against <b>{ctx['target']}</b> "
            f"on {ctx['generated_at']}. The assessment discovered <b>{ctx['total_hosts']}</b> "
            f"live host(s) with <b>{ctx['total_findings']}</b> security findings. "
            f"The overall risk is rated <b>{risk}</b>. "
        )
        if counts["Critical"] > 0:
            summary += f"<b>{counts['Critical']} CRITICAL issue(s) require immediate action within 24 hours.</b> "
        if counts["High"] > 0:
            summary += f"{counts['High']} HIGH severity issue(s) should be resolved within 7 days. "
        if ctx["total_findings"] == 0:
            summary += "No vulnerabilities were detected — the target appears well-secured against the tested vectors."
        story += [Paragraph(summary, BODY), blank(0.4)]

        # Risk guide table
        rg = Table([
            ["CRITICAL\n🚨 Fix in 24h", "HIGH\n🔴 Fix in 7 days",
             "MEDIUM\n🟠 Fix in 30 days", "LOW\n🔵 Fix when possible"],
            ["Full compromise\nor data theft possible",
             "Significant damage\nor breach likely",
             "Moderate risk,\nspecific conditions",
             "Minor risk,\nlimited impact"]
        ], colWidths=[4*cm]*4)
        rg.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (0,1), colors.HexColor("#fff0f0")),
            ("BACKGROUND",    (1,0), (1,1), colors.HexColor("#fff5f0")),
            ("BACKGROUND",    (2,0), (2,1), colors.HexColor("#fffbf0")),
            ("BACKGROUND",    (3,0), (3,1), colors.HexColor("#f0f6ff")),
            ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",      (0,0), (-1,-1), 8),
            ("ALIGN",         (0,0), (-1,-1), "CENTER"),
            ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#DDDDDD")),
            ("TOPPADDING",    (0,0), (-1,-1), 6),
            ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ]))
        story += [rg, PageBreak()]

        # ── METHODOLOGY ───────────────────────────────────────────────────────
        story += [Paragraph("Scan Methodology", H1), hr(), blank(0.2)]
        meth_data = [["Phase", "What Was Done", "What We Looked For"]] + \
                    [[m[0], m[1], m[2]] for m in ctx["methodology"]]
        mt = Table(meth_data, colWidths=[4*cm, 6*cm, 6*cm])
        mt.setStyle(TableStyle([
            ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
            ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
            ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE",      (0,0), (-1,-1), 8),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
            ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
            ("TOPPADDING",    (0,0), (-1,-1), 5),
            ("BOTTOMPADDING", (0,0), (-1,-1), 5),
            ("VALIGN",        (0,0), (-1,-1), "TOP"),
        ]))
        story += [mt, PageBreak()]

        # ── HOSTS ─────────────────────────────────────────────────────────────
        if ctx["hosts"]:
            story += [Paragraph("Discovered Hosts & Open Services", H1), hr(), blank(0.2)]
            for host in ctx["hosts"]:
                story.append(Paragraph(
                    f"<b>{host['ip']}</b> — {host.get('hostname','N/A')} — OS: {host.get('os','Unknown')}",
                    H2))
                if host.get("ports"):
                    pd = [["Port", "Service", "Version", "Security Note"]]
                    for p in host["ports"]:
                        note = ""
                        port = p.get("port", 0)
                        if port == 23:   note = "⚠️ Telnet — disable immediately"
                        elif port == 21: note = "⚠️ FTP unencrypted — use SFTP"
                        elif port == 3306: note = "⚠️ MySQL publicly exposed"
                        elif port == 3389: note = "⚠️ RDP — restrict by IP"
                        elif port == 80:   note = "Redirect to HTTPS"
                        pd.append([f"{port}/{p.get('protocol','tcp')}",
                                   p.get("service",""), str(p.get("version",""))[:30], note])
                    pt = Table(pd, colWidths=[2*cm, 2.5*cm, 5*cm, 6.5*cm])
                    pt.setStyle(TableStyle([
                        ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
                        ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
                        ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
                        ("FONTSIZE",      (0,0), (-1,-1), 8),
                        ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
                        ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                        ("TOPPADDING",    (0,0), (-1,-1), 4),
                        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
                    ]))
                    story.append(pt)
                story.append(blank(0.4))
            story.append(PageBreak())

        # ── WEB FINDINGS WITH PLAIN ENGLISH ───────────────────────────────────
        if ctx["web_findings"]:
            story += [Paragraph("Web Application Security Findings", H1), hr(), blank(0.2),
                      Paragraph("Each finding below includes a plain English explanation — what it is, what it means, what an attacker could do, and how to fix it.", BODY), blank(0.3)]
            for i, f in enumerate(ctx["web_findings"], 1):
                sev = f.get("severity","Low")
                sc  = SEV_COLORS.get(sev, NONE_CLR)
                block = []
                # Header
                hdr = Table([[
                    Paragraph(f"<b>{i}. {f.get('vuln_type','')}</b>", S("FH", fontSize=10, textColor=colors.HexColor("#222"), fontName="Helvetica-Bold")),
                    Paragraph(sev, S("SV", fontSize=9, textColor=sc, fontName="Helvetica-Bold", alignment=1))
                ]], colWidths=[13*cm, 3*cm])
                hdr.setStyle(TableStyle([
                    ("BACKGROUND",    (0,0), (-1,-1), colors.HexColor("#f8f9fa")),
                    ("TOPPADDING",    (0,0), (-1,-1), 8),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 8),
                    ("LEFTPADDING",   (0,0), (0,-1), 10),
                    ("LINEBELOW",     (0,0), (-1,0), 1, sc),
                ]))
                block.append(hdr)

                # Plain English grid
                pe_data = [
                    [Paragraph("<b>🔍 What is this?</b>", LABEL),
                     Paragraph("<b>💡 What does it mean?</b>", LABEL)],
                    [Paragraph(f.get("plain_what",""), PE),
                     Paragraph(f.get("plain_means",""), PE)],
                    [Paragraph("<b>💥 What could an attacker do?</b>", LABEL),
                     Paragraph("<b>🔧 How to fix it</b>", LABEL)],
                    [Paragraph(f.get("plain_impact",""), PE),
                     Paragraph(f.get("plain_fix","") + (f"\n\n⏱️ {f.get('plain_difficulty','')}" if f.get("plain_difficulty") else ""), PE)],
                ]
                pe_tbl = Table(pe_data, colWidths=[8*cm, 8*cm])
                pe_tbl.setStyle(TableStyle([
                    ("BACKGROUND",    (0,0), (-1,-1), colors.HexColor("#f0f8ff")),
                    ("BACKGROUND",    (0,2), (-1,2), colors.HexColor("#f0f8ff")),
                    ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#dde8f0")),
                    ("TOPPADDING",    (0,0), (-1,-1), 6),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 6),
                    ("LEFTPADDING",   (0,0), (-1,-1), 8),
                    ("VALIGN",        (0,0), (-1,-1), "TOP"),
                    ("LINEAFTER",     (0,0), (0,-1), 0.5, colors.HexColor("#c0d8ee")),
                ]))
                block.append(pe_tbl)

                # Technical details
                td = Table([
                    [Paragraph("<b>Technical Details</b>", LABEL), ""],
                    ["URL:", str(f.get("url",""))[:80]],
                    ["Evidence:", str(f.get("evidence","N/A"))[:80]],
                    ["Recommendation:", f.get("recommendation","")[:100]],
                ], colWidths=[3*cm, 13*cm])
                td.setStyle(TableStyle([
                    ("FONTSIZE",      (0,0), (-1,-1), 7.5),
                    ("FONTNAME",      (0,1), (0,-1), "Helvetica-Bold"),
                    ("TEXTCOLOR",     (0,1), (0,-1), colors.grey),
                    ("GRID",          (0,1), (-1,-1), 0.3, colors.HexColor("#EEEEEE")),
                    ("TOPPADDING",    (0,0), (-1,-1), 4),
                    ("BOTTOMPADDING", (0,0), (-1,-1), 4),
                    ("LEFTPADDING",   (0,0), (-1,-1), 6),
                    ("SPAN",          (0,0), (-1,0)),
                ]))
                block.append(td)
                block.append(blank(0.3))
                story.append(KeepTogether(block))
            story.append(PageBreak())

        # ── CVE FINDINGS ──────────────────────────────────────────────────────
        if ctx["cve_findings"]:
            story += [Paragraph("Known Software Vulnerabilities (CVEs)", H1), hr(), blank(0.2),
                      Paragraph("These are publicly documented security flaws found in software running on the target. Because they are publicly known, automated attack tools actively scan for them.", BODY), blank(0.3)]
            cve_tbl_data = [["CVE ID", "Host", "Port", "Service", "CVSS", "Severity", "Action"]]
            for f in ctx["cve_findings"]:
                cve_tbl_data.append([
                    f.get("cve_id",""), f.get("host_ip",""), str(f.get("port","")),
                    str(f.get("service",""))[:20], str(f.get("cvss_score","")),
                    f.get("severity",""), "Update software"
                ])
            ct = Table(cve_tbl_data, colWidths=[2.8*cm,2.5*cm,1.2*cm,3*cm,1.2*cm,2*cm,3.3*cm])
            ct.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
                ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
                ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE",      (0,0), (-1,-1), 8),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
                ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                ("TOPPADDING",    (0,0), (-1,-1), 4),
                ("BOTTOMPADDING", (0,0), (-1,-1), 4),
            ]))
            story += [ct, blank(0.4)]

            # CVE plain english descriptions
            for f in ctx["cve_findings"]:
                sev = f.get("severity","Low")
                sc  = SEV_COLORS.get(sev, NONE_CLR)
                score = float(f.get("cvss_score",0) or 0)
                if score >= 9.0:   impact_text = "EXTREMELY DANGEROUS — attacker can likely take full control of the server."
                elif score >= 7.0: impact_text = "HIGHLY DANGEROUS — can lead to significant data theft or system compromise."
                elif score >= 4.0: impact_text = "MODERATELY DANGEROUS — exploitation requires specific conditions."
                else:              impact_text = "LOW RISK — limited direct impact."

                cve_block = [
                    Paragraph(f"<b>{f.get('cve_id','')} — CVSS {f.get('cvss_score','')}/10 ({sev})</b>",
                              S("CH", fontSize=9, textColor=sc, fontName="Helvetica-Bold", spaceBefore=8)),
                    Paragraph(f"<b>Impact:</b> {impact_text}", PE),
                    Paragraph(f"<b>Description:</b> {f.get('description','See NVD for details.')[:200]}", PE),
                    Paragraph(f"<b>Fix:</b> Update {f.get('service','')} to the latest version. Search {f.get('cve_id','')} at nvd.nist.gov for patch details.", PE),
                    blank(0.2),
                ]
                story += cve_block
            story.append(PageBreak())

        # ── ACTION PLAN ───────────────────────────────────────────────────────
        story += [Paragraph("Your Action Plan — What To Do Next", H1), hr(), blank(0.2),
                  Paragraph("Address these issues in order of priority, starting from the top:", BODY), blank(0.2)]

        all_findings = ctx["all_findings"]
        if all_findings:
            ap_data = [["#", "Issue", "Severity", "Action Required"]]
            for i, f in enumerate(all_findings[:10], 1):
                sc = SEV_COLORS.get(f.get("severity","Low"), NONE_CLR)
                ap_data.append([
                    str(i),
                    f.get("vuln_type","")[:40],
                    f.get("severity",""),
                    f.get("recommendation","Fix this issue.")[:60]
                ])
            apt = Table(ap_data, colWidths=[0.8*cm, 6*cm, 2.5*cm, 6.7*cm])
            apt.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,0), DARK_BLUE),
                ("TEXTCOLOR",     (0,0), (-1,0), colors.white),
                ("FONTNAME",      (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE",      (0,0), (-1,-1), 8),
                ("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white, LIGHT_BLUE]),
                ("GRID",          (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
                ("TOPPADDING",    (0,0), (-1,-1), 5),
                ("BOTTOMPADDING", (0,0), (-1,-1), 5),
                ("VALIGN",        (0,0), (-1,-1), "TOP"),
            ]))
            story.append(apt)
        else:
            story.append(Paragraph("✅ No immediate actions required. Continue monitoring regularly.", BODY))

        # ── FOOTER ────────────────────────────────────────────────────────────
        story += [
            blank(1),
            hr(),
            blank(0.2),
            Paragraph(
                f"CyberScan Pro v1.0.0 | FUPRE Final Year Project | "
                f"Obeh Emmanuel Onoriode (Cos/9581/2022) | {ctx['generated_at']} | "
                f"⚠ This report is confidential. Authorized use only.",
                SMALL
            )
        ]

        doc.build(story)
